number = float(input("Введите число: "))
integer = int(input("Введите целое число: "))
text = input("Введите строку: ")
print("number =", number)
print("число - это", type(number))
print("число * 2 =", number * 2)
print("целое число =", integer)
print("целое число - это", type(integer))
print("целое число * 2 =", integer * 2)
print("текст =", text)
print("текст - это", type(text))
print("текст * 2 =", text * 2)
